### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by derelearnro** [PacktPublishing/Deep-Learning-with-PyTorch#3]
x_numpy = x.data.numpy()
plot_variable(x,y,'ro')
plot_variable(x,y_pred,label='Fitted line')

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-3687333e9a57> in <module>()
      1 x_numpy = x.data.numpy()
----> 2 plot_variable(x,y,'ro')
      3 plot_variable(x,y_pred,label='Fitted line')

<ipython-input-28-c2f34a268b8d> in plot_variable(x, y, z, **kwargs)
     15         if type(a) == Variable:
     16             l.append(a.data.numpy())
---> 17     plt.plot(l[0],l[1],z,**kwargs)
     18 
     19 def get_weights():

IndexError: list index out of range

Currently, I got a mistake with this error on chapter 2. Could you know why got this error and how can I solve it?

**Comment by herlimenezes** [comment]
I got the same error. I guessed it was related with this warning: "UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number". I have changed code without success.

**Comment by herlimenezes** [comment]
Hello, I have solved the plotting issues just dropping out the filter: "if type(a) == Variable:" so that the new function reads as:
`def plot_variable(x,y,z='',**kwargs):
    l = []
    for a in [x,y]:
        l.append(a.data.numpy())
    plt.plot(l[0],l[1],z,**kwargs)
`
The plot is then:
![image](https://user-images.githubusercontent.com/1139726/43468445-65553216-94ba-11e8-80c3-8830b897e365.png)

**Comment by yu-cheng-kuo-28** [comment]
Thx herlimenezes !
